name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests and generate coverage report
        run: ./gradlew testDebugUnitTest jacocoTestReport

      # Running hardware accelerated emulators on Linux runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run instrumented tests on emulator and generate coverage report
        uses: ReactiveCircus/android-emulator-runner@v2
        env:
          CI_COMPILE_SDK: 35
          CI_TARGET_SDK: 35
        with:
          api-level: 35
          arch: x86_64
          profile: Nexus 5
          disable-animations: true
          script: |
            adb wait-for-device
            ./gradlew connectedDebugAndroidTest jacocoTestDebugReport

      - name: Build and analyze
        working-directory: app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ../gradlew build sonar --info